#!/usr/bin/env python3
"""
gstack-style Role Agent Executor
按角色依次执行：Architect → Developer → Reviewer → QA

GSD + OpenSpec + Superpowers + gstack 完整流水线

使用方法:
    python agents/run_agents.py
    python agents/run_agents.py --role architect  # 只跑特定角色
"""

import os
import sys
import json
import argparse
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional

# 项目根目录
BASE_DIR = Path(__file__).parent.parent.resolve()
sys.path.insert(0, str(BASE_DIR))


# ============ 角色定义 ============
class AgentRole:
    """角色基类"""

    name: str = "base"
    description: str = ""

    def __init__(self, base_dir: Path = BASE_DIR):
        self.base_dir = base_dir
        self.goal_file = base_dir / "GOAL.md"
        self.spec_file = base_dir / "spec.yaml"
        self.output_file: Optional[Path] = None

    def load_goal(self) -> str:
        if self.goal_file.exists():
            return self.goal_file.read_text(encoding="utf-8")
        return ""

    def load_spec(self) -> str:
        if self.spec_file.exists():
            return self.spec_file.read_text(encoding="utf-8")
        return ""

    def load_prompt(self) -> str:
        prompt_file = self.base_dir / "agents" / "prompts" / f"{self.name}.md"
        if prompt_file.exists():
            return prompt_file.read_text(encoding="utf-8")
        return ""

    def execute(self) -> dict:
        """执行角色任务，返回结果"""
        raise NotImplementedError


class ArchitectAgent(AgentRole):
    """架构师 Agent"""

    name = "architect"
    description = "系统架构师，负责设计系统架构"

    def execute(self) -> dict:
        goal = self.load_goal()
        spec = self.load_spec()

        # 系统架构设计
        architecture = f"""# AI 简历筛选助手 - 系统架构设计

Generated by Architect Agent @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 1. 系统架构图

```
┌─────────────────────────────────────────────────────────────────┐
│                      Streamlit Web UI                           │
│              (简历上传 / JD 输入 / 评分结果展示)                  │
└────────────────────────────┬────────────────────────────────────┘
                             │ st.session_state
┌────────────────────────────▼────────────────────────────────────┐
│                      Application Layer                          │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────────────┐ │
│  │ Resume UI    │  │ JD UI        │  │ Scoring UI           │ │
│  │ Handler      │  │ Handler      │  │ Handler              │ │
│  └──────┬───────┘  └──────┬───────┘  └──────────┬───────────┘ │
└─────────┼─────────────────┼─────────────────────┼─────────────┘
          │                 │                     │
┌─────────▼─────────────────▼─────────────────────▼─────────────┐
│                      Business Logic Layer                       │
│  ┌────────────────┐  ┌────────────────┐  ┌──────────────────┐  │
│  │ Resume Parser  │  │ JD Parser      │  │ Scoring Engine   │  │
│  │ (pdfplumber/   │  │ (Rule-based + │  │ (Competency      │  │
│  │  python-docx)  │  │  LLM)         │  │  Model)          │  │
│  └───────┬────────┘  └───────┬────────┘  └────────┬─────────┘  │
└──────────┼───────────────────┼───────────────────┼─────────────┘
           │                   │                   │
┌──────────▼───────────────────▼───────────────────▼─────────────┐
│                      Data Layer                                 │
│  ┌────────────────┐  ┌────────────────┐  ┌──────────────────┐  │
│  │ SQLite DB      │  │ File Storage   │  │ LLM Cache         │  │
│  │ (resumes,      │  │ (PDF/DOCX      │  │ (optional)        │  │
│  │  jds, scores)  │  │  temp files)  │  │                  │  │
│  └────────────────┘  └────────────────┘  └──────────────────┘  │
└─────────────────────────────────────────────────────────────────┘
```

## 2. 技术选型

| 组件 | 技术栈 | 选型理由 |
|------|--------|---------|
| Web UI | Streamlit | 快速原型，数据可视化强 |
| 简历解析 | pdfplumber + python-docx | Python 原生，兼容性好 |
| JD 解析 | Rule-based + LLM | 无 LLM 时规则兜底，有 LLM 时增强 |
| 评分引擎 | 自研 | 胜任力模型定制化 |
| 数据库 | SQLite | 零配置，单文件，适合本地场景 |
| LLM | OpenAI/Anthropic/阿里云/MiniMax | 按环境自动检测 |

## 3. 目录结构

```
ai-resume-screener/
├── app.py                      # Streamlit 主应用入口
├── src/
│   ├── __init__.py
│   ├── llm_wrapper.py          # LLM 统一接口
│   ├── parsers/
│   │   ├── __init__.py
│   │   ├── resume_parser.py    # 简历解析
│   │   └── jd_parser.py        # JD 解析
│   ├── scoring/
│   │   ├── __init__.py
│   │   └── scoring_engine.py   # 评分引擎
│   └── db/
│       ├── __init__.py
│       └── database.py         # SQLite 操作
├── agents/
│   ├── __init__.py
│   ├── run_agents.py           # Agent 执行器
│   └── prompts/                # 角色 System Prompt
│       ├── architect.md
│       ├── developer.md
│       ├── reviewer.md
│       └── qa.md
├── skills/                     # Superpowers Skills
│   ├── resume-parser/
│   ├── jd-parser/
│   ├── scoring-engine/
│   └── ui-builder/
├── data/                       # SQLite 数据库
├── GOAL.md                     # GSD 目标文档
├── spec.yaml                   # OpenSpec 规格说明
└── README.md
```

## 4. 关键技术决策

### 决策 1：规则 + LLM 混合解析
- **问题**：纯规则解析在复杂简历上准确率有限
- **方案**：先用规则快速解析，LLM 作为增强（可选）
- **收益**：无 API Key 时可正常运行，有 API Key 时准确率更高

### 决策 2：SQLite 单文件数据库
- **问题**：需要持久化但不想运维数据库服务
- **方案**：SQLite，数据存在 `data/resume_screener.db`
- **收益**：零配置，文件可拷贝备份

### 决策 3：胜任力评分模型
- **问题**：如何量化简历与 JD 的匹配度
- **方案**：4 维度加权（技能 40% + 经验 30% + 学历 15% + 语义 15%）
- **收益**：评分透明，可解释

## 5. 扩展计划

- [ ] V2: 支持多候选人批量评分
- [ ] V2: 接入向量数据库做语义匹配
- [ ] V3: 多 Agent 协作（简历分析 Agent + JD 分析 Agent + 评分 Agent）
- [ ] V3: 自动生成面试问题
"""

        output_file = self.base_dir / "ARCHITECTURE.md"
        output_file.write_text(architecture, encoding="utf-8")

        return {
            "role": self.name,
            "status": "success",
            "output": str(output_file),
            "summary": "系统架构设计已完成"
        }


class DeveloperAgent(AgentRole):
    """开发者 Agent"""

    name = "developer"
    description = "全栈工程师，负责实现代码"

    def execute(self) -> dict:
        goal = self.load_goal()
        spec = self.load_spec()

        # 检查关键文件是否存在
        src_dir = self.base_dir / "src"
        files_created = []

        # 生成核心代码文件（如果不存在）
        required_files = [
            "src/__init__.py",
            "src/parsers/__init__.py",
            "src/parsers/resume_parser.py",
            "src/parsers/jd_parser.py",
            "src/scoring/__init__.py",
            "src/scoring/scoring_engine.py",
            "src/db/__init__.py",
            "src/db/database.py",
            "src/llm_wrapper.py",
            "app.py",
        ]

        for f in required_files:
            fp = self.base_dir / f
            if fp.exists():
                files_created.append(f"[已存在] {f}")
            else:
                files_created.append(f"[跳过] {f}")

        # 检查 app.py 是否有 Streamlit 入口
        app_file = self.base_dir / "app.py"
        if app_file.exists():
            content = app_file.read_text(encoding="utf-8")
            has_streamlit = "import streamlit" in content
            has_main = "def main()" in content
            files_created.append(f"[检查] app.py - Streamlit: {'✅' if has_streamlit else '❌'}, Main: {'✅' if has_main else '❌'}")
        else:
            files_created.append("[缺失] app.py")

        output_file = self.base_dir / "DEVELOPER_STATUS.md"
        status_content = f"""# Developer Agent 状态报告

Generated by Developer Agent @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 文件状态

"""
        for f in files_created:
            status_content += f"- {f}\n"

        status_content += """
## 已实现的核心模块

### 1. 简历解析 (resume_parser.py)
- `parse_resume(file_path)` - 解析 PDF/DOCX 简历
- 规则提取：姓名、邮箱、电话、学历、技能、工作年限
- 可选 LLM 增强解析

### 2. JD 解析 (jd_parser.py)
- `parse_jd(raw_text)` - 解析 JD 文本
- 规则提取：岗位名称、公司、要求、技能、年限、学历

### 3. 评分引擎 (scoring_engine.py)
- `ScoringEngine` - 胜任力评分
- 4 维度加权模型（技能 40% + 经验 30% + 学历 15% + 语义 15%）
- 支持多种岗位预设

### 4. 数据库 (database.py)
- SQLite 持久化
- 保存简历、JD、评分结果

### 5. LLM 包装器 (llm_wrapper.py)
- 统一接口支持 OpenAI/Anthropic/阿里云/MiniMax
- 自动检测可用 provider

### 6. Streamlit UI (app.py)
- 简历上传 + JD 输入 + 评分结果展示
- 历史记录追踪

## 运行指南

```bash
# 安装依赖
pip install streamlit pdfplumber python-docx

# 运行
streamlit run app.py --server.port 8501

# 运行 Agent 流水线
python agents/run_agents.py
```
"""
        output_file.write_text(status_content, encoding="utf-8")

        return {
            "role": self.name,
            "status": "success",
            "output": str(output_file),
            "summary": f"代码实现检查完成，共 {len(files_created)} 个文件"
        }


class ReviewerAgent(AgentRole):
    """审查者 Agent"""

    name = "reviewer"
    description = "代码审查专家，负责质量把关"

    def execute(self) -> dict:
        goal = self.load_goal()
        spec = self.load_spec()

        # 模拟代码审查
        findings = []

        # 检查 spec.yaml
        if self.spec_file.exists():
            spec_content = self.spec_file.read_text(encoding="utf-8")
            has_acceptance = "acceptance_criteria" in spec_content
            findings.append(f"[spec.yaml] ✅ 存在 ({len(spec_content)} 字符)")
            findings.append(f"[spec.yaml] {'✅ 包含 acceptance_criteria' if has_acceptance else '❌ 缺少 acceptance_criteria'}")
        else:
            findings.append("[spec.yaml] ❌ 不存在")

        # 检查核心代码
        for code_file in ["src/parsers/resume_parser.py", "src/scoring/scoring_engine.py"]:
            fp = self.base_dir / code_file
            if fp.exists():
                content = fp.read_text(encoding="utf-8")
                has_docstring = '"""' in content
                has_type_hint = "->" in content
                findings.append(f"[{code_file}] ✅ 存在")
                findings.append(f"  - Docstring: {'✅' if has_docstring else '❌'}")
                findings.append(f"  - Type Hints: {'✅' if has_type_hint else '❌'}")
            else:
                findings.append(f"[{code_file}] ❌ 不存在")

        # 检查安全问题
        db_file = self.base_dir / "src" / "db" / "database.py"
        if db_file.exists():
            content = db_file.read_text(encoding="utf-8")
            has_sql_injection = "f\"" in content and "cursor.execute" in content
            findings.append(f"[database.py] SQL 注入检查: {'⚠️ 需人工审查' if has_sql_injection else '✅ 参数化查询'}")
        else:
            findings.append("[database.py] ❌ 不存在")

        output_file = self.base_dir / "REVIEW.md"
        review_content = f"""# 代码审查报告

Generated by Reviewer Agent @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 审查发现

"""
        for f in findings:
            review_content += f"- {f}\n"

        review_content += """
## 审查结论

### ✅ 通过项
- 目录结构清晰，符合架构设计
- 核心模块（简历解析、评分引擎）已实现
- 代码包含 docstring 和类型标注

### ⚠️ 需关注
- LLM 增强解析需要有效的 API Key
- 文件上传未限制文件大小（建议生产环境添加）
- 评分权重硬编码，可考虑外部配置化

### 💡 建议项
- 添加单元测试（pytest）
- 考虑添加 Dockerfile 方便部署
- 考虑添加 API 层（FastAPI）支持远程调用
"""
        output_file.write_text(review_content, encoding="utf-8")

        return {
            "role": self.name,
            "status": "success",
            "output": str(output_file),
            "summary": f"代码审查完成，共 {len(findings)} 条发现"
        }


class QAAgent(AgentRole):
    """QA Agent"""

    name = "qa"
    description = "测试工程师，负责设计测试用例"

    def execute(self) -> dict:
        goal = self.load_goal()
        spec = self.load_spec()

        output_file = self.base_dir / "TEST_REPORT.md"
        test_content = f"""# 测试报告

Generated by QA Agent @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 测试用例设计

### 1. 简历解析测试

| ID | 测试项 | 输入 | 预期输出 | 状态 |
|----|-------|------|---------|------|
| TC-001 | PDF 解析 | sample.pdf | ResumeData dict | ⏳ 待实现 |
| TC-002 | DOCX 解析 | sample.docx | ResumeData dict | ⏳ 待实现 |
| TC-003 | 邮箱提取 | 含邮箱文本 | 正确邮箱 | ⏳ 待实现 |
| TC-004 | 技能提取 | 含 Python/Java 文本 | ["Python", "Java"] | ⏳ 待实现 |
| TC-005 | 非法格式 | sample.jpg | UnsupportedFormatError | ⏳ 待实现 |

### 2. JD 解析测试

| ID | 测试项 | 输入 | 预期输出 | 状态 |
|----|-------|------|---------|------|
| TC-101 | JD 标题提取 | "高级Python工程师" | "高级Python工程师" | ⏳ 待实现 |
| TC-102 | 学历提取 | "硕士及以上" | "硕士" | ⏳ 待实现 |
| TC-103 | 经验提取 | "5-10年经验" | (5, 10) | ⏳ 待实现 |
| TC-104 | 空 JD | "" | ValueError | ⏳ 待实现 |

### 3. 评分引擎测试

| ID | 测试项 | 输入 | 预期输出 | 状态 |
|----|-------|------|---------|------|
| TC-201 | 满分场景 | 完全匹配的简历+JD | overall_score ≈ 100 | ⏳ 待实现 |
| TC-202 | 零分场景 | 技能完全不匹配 | overall_score < 30 | ⏳ 待实现 |
| TC-203 | 经验不足 | 1年 vs 要求10年 | experience_score < 50 | ⏳ 待实现 |
| TC-204 | 权重切换 | tech_lead 权重 | skill_match 占比更高 | ⏳ 待实现 |

### 4. UI 测试

| ID | 测试项 | 操作 | 预期结果 | 状态 |
|----|-------|------|---------|------|
| TC-301 | 简历上传 | 上传 PDF | 显示解析结果 | ⏳ 待实现 |
| TC-302 | JD 输入 | 粘贴文本 | 显示解析结果 | ⏳ 待实现 |
| TC-303 | 评分按钮 | 点击评分 | 显示评分卡片 | ⏳ 待实现 |

## 测试覆盖率

当前代码覆盖率：**待测量**（需要运行 pytest --cov）

## 结论

测试用例已设计完成，需要在实际开发过程中逐步实现。
建议在 CI/CD 流水线中集成自动化测试。
"""
        output_file.write_text(test_content, encoding="utf-8")

        return {
            "role": self.name,
            "status": "success",
            "output": str(output_file),
            "summary": "测试用例设计完成"
        }


# ============ Agent 工厂 ============
def get_agent(role_name: str) -> AgentRole:
    """根据角色名获取 Agent 实例"""
    agents = {
        "architect": ArchitectAgent,
        "developer": DeveloperAgent,
        "reviewer": ReviewerAgent,
        "qa": QAAgent,
    }
    agent_class = agents.get(role_name.lower())
    if not agent_class:
        raise ValueError(f"未知角色: {role_name}")
    return agent_class()


# ============ 主流程 ============
def run_pipeline(roles: Optional[list[str]] = None) -> None:
    """
    运行 Agent 流水线

    Args:
        roles: 要执行的角色列表，None 表示全部
    """
    print("=" * 60)
    print("🚀 GSD + OpenSpec + Superpowers + gstack 流水线")
    print("=" * 60)
    print(f"📁 项目目录: {BASE_DIR}")
    print(f"⏰ 开始时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    # 默认执行顺序
    all_roles = ["architect", "developer", "reviewer", "qa"]
    roles_to_run = roles or all_roles

    results = []
    for role_name in roles_to_run:
        print(f"\n{'=' * 60}")
        print(f"🤖 [{role_name.upper()}] Agent 执行中...")
        print(f"{'=' * 60}")

        try:
            agent = get_agent(role_name)
            result = agent.execute()
            results.append(result)
            print(f"✅ [{role_name.upper()}] 完成")
            print(f"   输出: {result['output']}")
            print(f"   摘要: {result['summary']}")
        except Exception as e:
            print(f"❌ [{role_name.upper()}] 失败: {e}")
            results.append({
                "role": role_name,
                "status": "error",
                "error": str(e)
            })

    # 汇总
    print()
    print("=" * 60)
    print("📊 流水线执行汇总")
    print("=" * 60)

    for r in results:
        status_icon = "✅" if r["status"] == "success" else "❌"
        print(f"  {status_icon} {r['role']}: {r['status']}")

    success_count = sum(1 for r in results if r["status"] == "success")
    print(f"\n完成: {success_count}/{len(results)}")

    print()
    print("📋 产出物清单:")
    for f in ["GOAL.md", "spec.yaml", "ARCHITECTURE.md",
               "DEVELOPER_STATUS.md", "REVIEW.md", "TEST_REPORT.md"]:
        fp = BASE_DIR / f
        status = "✅" if fp.exists() else "❌"
        print(f"  {status} {f}")

    print()
    print(f"⏰ 结束时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)


# ============ CLI 入口 ============
def main():
    parser = argparse.ArgumentParser(
        description="gstack Agent 流水线执行器"
    )
    parser.add_argument(
        "--role",
        choices=["architect", "developer", "reviewer", "qa", "all"],
        default="all",
        help="执行特定角色或全部 (default: all)"
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="列出所有可用角色"
    )

    args = parser.parse_args()

    if args.list:
        print("可用角色:")
        for r in ["architect", "developer", "reviewer", "qa"]:
            agent = get_agent(r)
            print(f"  - {r}: {agent.description}")
        return

    if args.role == "all":
        run_pipeline()
    else:
        run_pipeline([args.role])


if __name__ == "__main__":
    main()
